/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

int main(void)
{

    RCC->AHB1ENR |= (0b1 << 0);
    GPIOA->MODER &= ~(0b11 << (5 * 2));
    GPIOA->MODER |= (0b01 << (5 * 2));
    GPIOA->OTYPER &= ~(0b1 << 5);
    GPIOA->OSPEEDR &= ~(0b11 << (5 * 2));
    GPIOA->OSPEEDR |= (0b10 << (5 * 2));
    GPIOA->PUPDR &= ~(0b11 << (5 * 2));

    RCC->AHB1ENR |= (0b1 << 2);
    GPIOC->MODER &= ~(0b11 << (13 * 2));
    GPIOC->PUPDR &= ~(0b11 << (13 * 2));

    while(1){

        if ((GPIOC->IDR & (1 << 13)) == 0) {

            GPIOA->ODR |= (1 << 5);
            } 
        else {
                GPIOA->ODR &= ~(1 << 5);
        }

    }

}

