/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xe.h"
#include "stm32f4xx.h"

// Headers definitios
void init_gpio(void);
void init_tim3(void);

int main(void)
{
    // Configurar el hardware antes de la funcion principal
    init_gpio();

    init_tim3(); // Cargar la configuracion del timer
    
    /* Loop forever */
	while(1){

    }

    return 0;

}

void init_gpio(void){
    // Encender la señal de reloj para el GPIOA    
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN_Msk;

    // Configurar el PIN A5 como salida push_pull
    GPIOA->MODER &= ~(0b11 << GPIO_MODER_MODER5_Pos); // Limpiar la posicion
    GPIOA->MODER |= (0b01 << GPIO_MODER_MODER5_Pos); // Configuramos A5 como salida

    GPIOA->OTYPER &= ~(GPIO_OTYPER_OT5_Pos); // Limpiamos la posicion, configuramos como salida push_pull
    
    GPIOA->OSPEEDR &= ~(0b11 << GPIO_OSPEEDR_OSPEED5_Pos); // Limpiamos la posicion
    GPIOA->OSPEEDR |= (0b01 << GPIO_OSPEEDR_OSPEED5_Pos); // Configuramos la velocidad

    GPIOA->PUPDR &= ~(0b11 << GPIO_PUPDR_PUPD5_Pos); // Limpiamos la posicion, configuramos pullup pulldown

    GPIOA->ODR |= GPIO_ODR_OD5; // Encendemos el LED verde del nucleo

}

/*
Configuracion del tim3 para generar una interrupcion cada 0.25 s
*/
void init_tim3(void){

    // Encendemos la señal de reloj para el TIM·
    RCC->APB1ENR |= RCC_AHB1ENR_GPIOBEN_Msk;

    // Configuracion de TIM3
    TIM3->CNT = 0;
    TIM3->PSC = (1600 - 1); // Para incrementar el CNT cada 0.1 us
    TIM3->ARR = (2500 - 1); // Se generan eventos de actualizacion cada 0.25 s

    TIM3->CR1 &= ~(0b11 << TIM_CR1_CKD_Pos); // Limpia, la señal de 16MHz pasa sin cambios 
    TIM3->CR1 |= TIM_CR1_ARPE; // Activo el pre-load del ARR
    TIM3->CR1 &= ~TIM_CR1_DIR; // Limpia, configura conteo ascendente

    TIM3->DIER |= TIM_DIER_UIE; // Activamos la interrupcion por evento de actualizacion
    
    NVIC_EnableIRQ(TIM3_IRQn); // Registrar la interrupcion TIM3 en el NVIC

    // Activar el contador - to-do
    TIM3->CR1 |= TIM_CR1_CEN;
}

/*
ISR del TIM3
Funcion que "administra" la interrupcion del TIM3
*/
void TIM3_IRQHandler(void){
    // Verificar que la bandera esta en alto
    if(TIM3->SR && TIM_SR_UIF){
        TIM3->SR &= ~TIM_SR_UIF; // Bajando la bandera de la interrupcion

        // Hacemos "algo" en la interrupcion
        GPIOA->ODR ^= GPIO_ODR_OD5; // Hacemos un toogle en la posicion 5 del GPIOA
    }
}
