/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    /* Loop forever */
	while(1){

    }
}

//2.1
uint8_t value = 0b10110101;
uint8_t mask = 0b00001111;
uint8_t result = value & mask;

//2.2
uint8_t value = 0b10100000;
uint8_t mask = 0b00000101;
uint8_t result = value | mask;

//2.3
uint8_t a = 0b00001111;
uint8_t result1 = ~a;
uint8_t b = 0b10100101;
uint8_t result2 = ~b;

//2.4
uint8_t value = 0b10110011;
uint8_t mask = 0b00001111;
uint8_t result1 = value ^ mask;
uint8_t result2 = result1 ^ mask;

